<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class LebaranSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Projected Dates for Idul Fitri (1 Syawal)
        // Source: Approximations based on 1443-1456 H
        $data = [
            ['tahun' => 2022, 'tahun_hijriyah' => '1443 H', 'tanggal' => '2022-05-02'],
            ['tahun' => 2023, 'tahun_hijriyah' => '1444 H', 'tanggal' => '2023-04-22'],
            ['tahun' => 2024, 'tahun_hijriyah' => '1445 H', 'tanggal' => '2024-04-10'],
            ['tahun' => 2025, 'tahun_hijriyah' => '1446 H', 'tanggal' => '2025-03-31'],
            ['tahun' => 2026, 'tahun_hijriyah' => '1447 H', 'tanggal' => '2026-03-20'],
            ['tahun' => 2027, 'tahun_hijriyah' => '1448 H', 'tanggal' => '2027-03-09'],
            ['tahun' => 2028, 'tahun_hijriyah' => '1449 H', 'tanggal' => '2028-02-26'],
            ['tahun' => 2029, 'tahun_hijriyah' => '1450 H', 'tanggal' => '2029-02-14'],
            ['tahun' => 2030, 'tahun_hijriyah' => '1451 H', 'tanggal' => '2030-02-04'],
            ['tahun' => 2031, 'tahun_hijriyah' => '1452 H', 'tanggal' => '2031-01-24'],
            ['tahun' => 2032, 'tahun_hijriyah' => '1453 H', 'tanggal' => '2032-01-14'],
            ['tahun' => 2033, 'tahun_hijriyah' => '1454 H', 'tanggal' => '2033-01-02'],
            ['tahun' => 2034, 'tahun_hijriyah' => '1455 H', 'tanggal' => '2033-12-23'], // 2033 has two, treating 2nd as 2034 context or just stored
            ['tahun' => 2035, 'tahun_hijriyah' => '1456 H', 'tanggal' => '2034-12-12'], 
        ];

        foreach ($data as $item) {
            DB::table('md_lebaran')->updateOrInsert(
                ['tahun' => $item['tahun']], // Key to check
                [
                    'tahun_hijriyah' => $item['tahun_hijriyah'],
                    'tanggal' => $item['tanggal'],
                    'keterangan' => 'Generated by System',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'is_deleted' => false
                ]
            );
        }
    }
}
